config/routes.rb
Rails.application.routes.draw do

root 'audits#index'
get '/404audit', :to => redirect('/404audit.html')

get '/login' => 'session#new', as: 'login'
post '/login' => 'session#create'
get '/logout' => 'session#destroy', as: 'logout'

resources :audits, only: [:new, :create, :index, :destroy, :update]
get 'audits/:id/edit/:subtype' => 'audits#edit', as: 'edit_audit'

resources :five_minute_summaries, only: [:show, :edit, :update]
resources :content_blocks, only: [:edit, :update, :destroy]
resources :background_photos, only: [:show, :destroy]

resources :users, only: [:new, :create, :edit, :update, :destroy, :index]

get '/shared_media_library' => 'shared_media_library#index', as: 'shared_media_library'
get '/shared_media_library/:id' => 'shared_media_library#show', as: 'shared_media_library_item'
post '/shared_media_library' => 'shared_media_library#create'
delete '/shared_media_library/:id' => 'shared_media_library#destroy'

get '/:audit_id/media_library' => 'media_library#index', as: 'media_library'
get '/:audit_id/media_library/:id' => 'media_library#show', as: 'media_library_item'
post '/:audit_id/media_library' => 'media_library#create'
delete '/:audit_id/media_library/:id' => 'media_library#destroy'


get '/content_blocks/new/:sectionid/:position' => 'content_blocks#new', as: 'new_content_block'
post '/content_blocks/new/:sectionid/:position' => 'content_blocks#create'

post '/content_blocks/cbhelper/:helper_type' => 'content_blocks#cbhelper', as: 'content_block_helper'

resources :full_audits, only: [:show, :edit, :update]
resources :sections, only: [:edit, :update, :destroy]

get '/sections/new/:full_audit_id/:position' => 'sections#new', as: 'new_section'
post '/sections/new/:full_audit_id/:position' => 'sections#create'

get 'publish/:switch/:id' => 'public_views#publish', as: 'publish'


get '/public/audits/:id/five_minute_summary' => 'public_views#fms', as: 'public_five_minute_summary'
get '/public/audits/:id/full_audit' => 'public_views#fa', as: 'public_full_audit'

end

app/controllers/media_library_controller.rb
class MediaLibraryController < ApplicationController
 layout "admin"

	def index
		@audit = Audit.find(params[:audit_id])
		@allphotos = @audit.inline_photos
		@newphoto = InlinePhoto.new
	end

	def show
		@photo = InlinePhoto.find(params[:id])
	end

	def create
		audit = Audit.find(params[:audit_id])
		if params[:inline_photo]
			newfile = params[:inline_photo][:photo]
		end

		if newfile.nil?
			flash[:error] = "Sorry, Please choose a file to upload"
		else
			newphoto = InlinePhoto.new(photo: newfile)
			if newphoto.valid?
				audit.inline_photos << newphoto
			else
				flash[:error] = "Sorry, we're unable to upload that file"
			end
		end
		redirect_to media_library_url

	end

	def destroy
		photo_to_delete = InlinePhoto.find(params[:id])
		photo_to_delete.destroy
		redirect_to :back

	end

end

app/views/media_library/index.html.erb
<div class="row">
	<div class="small-12 columns">
		
		<div class="row">
			<div class="small-1 columns">
				Media<br><strong>Library</strong> for 
			</div>
			<div class="small-11 columns end">
				<strong><%= simple_format(@audit.name, {}, wrapper_tag: "span").gsub(/\n/, '').html_safe %></strong>
			</div>
		</div>
		

		<div class="backpanel">
			<div class="row">
				<div class="small-2 columns">
					<h5>Add <strong>Media</strong></h5>
					<h6><small>(png, gif or jpeg only)</small></h6>
				</div>
				<div class="small-10 columns">
					<div class="row">
						<div class="small-12">
							<% if flash[:error] %>
								<div data-alert class="alert-box alert">
							  	<%= flash[:error] %>
								  <a href="#" class="close">&times;</a>
								</div>
							<% end %>
						</div>
					</div>
					
						<%= form_for @newphoto, url: media_library_url(@audit) do |f| %>
						<div class="row">
							<div class="small-6">
								<%= f.file_field :photo, label: "&nbsp;".html_safe, accept: 'image/png,image/gif,image/jpeg' %>
							</div>
							<div class="small-6">
								<%= f.submit 'Add media', class: "tiny radius success button" %>
							</div>
						</div>
						<% end %>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="small-12 columns">		
				<% if @allphotos %>
					<ul class="small-block-grid-2 medium-block-grid-4 large-block-grid-6">
						<%= render partial: 'shared/media_library_item', collection: @allphotos %>
					</ul>
				<% end %>
			</div>
		</div>

	</div>
</div>

<!-- BEGIN SECTION SPACER -->
<div class="RASectionSpacer">

</div>
<!-- END SECTION SPACER -->

<% content_for :admin_footer do %>
  
<div id="adminfooter">
	<div class="wrap">
		<div class="row">

			<div class="small-3 columns leftadminmenu">
				<div class="small-3 columns text-right">
			    <%= link_to audits_url do %>
			      <small>Back to All<br><strong>Audits</strong> </small>
			    <% end %>
				</div>
				<div class="small-9 columns text-left">
					<strong><%= simple_format(@audit.name, {}, wrapper_tag: "span").gsub(/\n/, '').html_safe %></strong> 
				</div>
			</div>

			<div class="small-9 columns rightadminmenu">
				<div class="small-2 columns text-left">
				<%= link_to five_minute_summary_url(@audit.five_minute_summary) do %> 	
					View<br><strong>Five Minute Summary</strong>
				<% end %>
				</div>
				<div class="small-2 columns text-left">
					<%= link_to edit_five_minute_summary_url(@audit.five_minute_summary) do %> 
						Edit<br><strong>Five Minute Summary</strong>
					<% end %>
				</div>
				<div class="small-2 columns text-left">
					<%= link_to full_audit_url(@audit.full_audit) do %>
						View<br><strong>Full Audit</strong>
					<% end %>
				</div>
				<div class="small-2 columns text-left">
					<%= link_to edit_full_audit_url(@audit.full_audit) do %> 
						Edit<br><strong>Full Audit</strong>
					<% end %>
				</div>
				<div class="small-1 columns text-left admin-nav-active">
					 
						Media<br><strong>Library</strong>
					
				</div>
	      <div class="small-3 columns text-right">
	        Los Angeles Controller <strong>Audits</strong><br>
	        Welcome, <strong><%= @current_user.email %></strong><br>
	        <%= link_to 'Logout', logout_url %>
	      </div>
			</div>


		</div>
	</div>
</div>

<% end %>

app/views/media_library/show.html.erb
<p><%= image_tag @photo.photo.url(:medium) %><br>
<small><%= @photo.photo_file_name %></small>
</p>
<%= button_to "Delete This Photo", shared_media_library_item_url(@photo), :method => 'delete', data: { :confirm => 'Are you sure you want to delete this photo?'} , class: "tiny radius alert button" %>

<a class="close-reveal-modal">&#215;</a>