config/routes.rb
Rails.application.routes.draw do

root 'audits#index'
get '/404audit', :to => redirect('/404audit.html')

get '/login' => 'session#new', as: 'login'
post '/login' => 'session#create'
get '/logout' => 'session#destroy', as: 'logout'

resources :audits, only: [:new, :create, :index, :destroy, :update]
get 'audits/:id/edit/:subtype' => 'audits#edit', as: 'edit_audit'

resources :five_minute_summaries, only: [:show, :edit, :update]
resources :content_blocks, only: [:edit, :update, :destroy]
resources :background_photos, only: [:show, :destroy]

resources :users, only: [:new, :create, :edit, :update, :destroy, :index]

get '/shared_media_library' => 'shared_media_library#index', as: 'shared_media_library'
get '/shared_media_library/:id' => 'shared_media_library#show', as: 'shared_media_library_item'
post '/shared_media_library' => 'shared_media_library#create'
delete '/shared_media_library/:id' => 'shared_media_library#destroy'

get '/:audit_id/media_library' => 'media_library#index', as: 'media_library'
get '/:audit_id/media_library/:id' => 'media_library#show', as: 'media_library_item'
post '/:audit_id/media_library' => 'media_library#create'
delete '/:audit_id/media_library/:id' => 'media_library#destroy'


get '/content_blocks/new/:sectionid/:position' => 'content_blocks#new', as: 'new_content_block'
post '/content_blocks/new/:sectionid/:position' => 'content_blocks#create'

post '/content_blocks/cbhelper/:helper_type' => 'content_blocks#cbhelper', as: 'content_block_helper'

resources :full_audits, only: [:show, :edit, :update]
resources :sections, only: [:edit, :update, :destroy]

get '/sections/new/:full_audit_id/:position' => 'sections#new', as: 'new_section'
post '/sections/new/:full_audit_id/:position' => 'sections#create'

get 'publish/:switch/:id' => 'public_views#publish', as: 'publish'


get '/public/audits/:id/five_minute_summary' => 'public_views#fms', as: 'public_five_minute_summary'
get '/public/audits/:id/full_audit' => 'public_views#fa', as: 'public_full_audit'

end

app/models/user.rb
class User
	include Mongoid::Document
	include ActiveModel::SecurePassword 	# this, along with the 
																				# 'has_secure_password' below
																				# enables all the pwd hashing

	field :email, type: String
	field :password_digest, type: String
	field :administrator, type: Boolean

	validate :email, presence: true, uniqueness: true

	has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	layout "admin"


	def index
		@users = User.all

	end

	def new
		@newuser = User.new

	end

	def create

		if User.where(email: params[:user][:email]).exists?

			flash.now[:notice] = "Someone else is already using that email address"
			@newuser = User.new
			render :new

		elsif params[:user][:email].blank?

			flash.now[:notice] = "Email field cannot be blank"
			@newuser = User.new
			render :new

		elsif params[:user][:password].blank? || params[:user][:password_confirmation].blank?

			flash.now[:notice] = "Password fields can't be blank"
			@newuser = User.new
			render :new

		elsif params[:user][:password] != params[:user][:password_confirmation]

			flash.now[:notice] = "Passwords did not match"
			@newuser = User.new
			render :new

		else

			user = User.new
			user.email = params[:user][:email]
			user.password = params[:user][:password]
			user.password_confirmation = params[:user][:password_confirmation]
			user.save!
			redirect_to users_url

		end

	end

	def edit
		@user = User.find(params[:id])
	end

	def update

		@user = User.find(params[:id])		

		case params[:update_type]
		when 'email'
			if params[:user][:email].blank?
				flash.now[:notice] = "Email field cannot be blank"
				@newuser = User.new
				render :edit
			elsif @user.email == params[:user][:email]
				@newuser = User.new
				render :edit
			elsif User.where(email: params[:user][:email]).exists?
				flash.now[:notice] = "Someone else is already using that email address"
				render :edit
			else
				flash.now[:notice] = "Email has been changed from #{@user.email} to #{params[:user][:email]}"
				@user.email = params[:user][:email]
				@user.save!
				redirect_to users_path
			end

		when 'password'

			if params[:user][:new_password].blank? || params[:user][:new_password_confirmation].blank?
				flash.now[:notice] = "Password fields cannot be blank"
				@newuser = User.new
				render :edit
			elsif params[:user][:new_password] != params[:user][:new_password_confirmation]
				flash.now[:notice] = "Passwords must match"
				@newuser = User.new
				render :edit				
			else
				@user.password = params[:user][:new_password]
				@user.password_confirmation = params[:user][:new_password_confirmation]
				flash.now[:notice] = "You have changed your password"
				@user.save!
				redirect_to users_path
			end

		end


	end

	def destroy
		user_to_nix = User.find(params[:id])
		user_to_nix.destroy
		redirect_to users_url, notice: "You have successfully deleted the user #{user_to_nix.email}."
	end


end

app/views/users/_user.html.erb
<div class="row">
	<div class="small-5 columns">
		<strong><%= user.email %></strong>
	</div>

	<div class="small-7 columns">
		<%= link_to edit_user_url(user) do %>
			<i class="fi-pencil"></i> <small>Edit User</small>
		<% end %><br/>

		
		<a href="#" data-reveal-id="myModal_<%= user.id %>">
			<i class="fi-x"></i> <small>Delete this User</small>
		</a>


	</div>

</div>

<div id="myModal_<%= user.id %>" class="reveal-modal small" data-reveal>
	<h2>Delete <strong>User</strong></h2>
  	<div class="AdminSectionSpacer1"></div>
  	<h4><strong><%= user.email %></strong></h4>

		<h6>Are you sure you want to delete this user?<br>
			<strong style="color: red;">All Deletions are Final</strong>
		</h6>
		<div class="AdminSectionSpacer1"></div>
  <%= button_to "Yes, Delete", user_path(user), :method => 'delete', data: { :confirm => 'Are you sure you want to delete this user?'} , class: "tiny radius alert button" %> <a class="tiny radius info button custom-close-reveal-modal">No, I've changed my mind!!!</a>
  <a class="close-reveal-modal">&#215;</a>
</div>

app/views/users/edit.html.erb
<div class="row">
	<div class="small-4 columns">
		<h2>Edit<br><strong>User - <%=@user.email%></strong></h2>
		<% if flash[:notice] %>
				<div data-alert class="alert-box alert round">
			  	<%= flash[:notice] %>
				  <a href="#" class="close">&times;</a>
				</div>
		<% end %>
	</div>
</div>

<div class="row">
	
		<div class="small-5 columns">
			<h4>Change<br><strong>email</strong></h4>
			<div class="backpanel">
				<%= form_for @user, url: user_path(@user) do |f| %>
					<%= hidden_field_tag 'update_type', 'email' %>
					<%= f.text_field :email %>
					<%= f.submit 'Change email', class: "tiny radius success button" %> <%= link_to 'Cancel', users_path, class: "tiny radius info button"  %>
				<% end %>
			</div>
		</div>
		
</div>

<div class="row">
	
		<div class="small-5 columns">
			<h4>Change<br><strong>password</strong></h4>
			<div class="backpanel">
				<%= form_for @user, url: user_path(@user) do |f| %>
					<%= hidden_field_tag 'update_type', 'password' %>
					<%= f.password_field :new_password %>
					<%= f.password_field :new_password_confirmation %>
					<%= f.submit 'Change password', class: "tiny radius success button" %> <%= link_to 'Cancel', users_path, class: "tiny radius info button"  %>
				<% end %>			
			</div>
		</div>

</div>


<% content_for :admin_footer do %>

<!-- BEGIN SECTION SPACER -->
<div class="RASectionSpacer">

</div>
<!-- END SECTION SPACER -->
<div id="adminfooter">
  <div class="wrap">
    <div class="row">
  
		  <div class="small-4 columns leftadminmenu">
		    <div class="small-12 columns">
		      <%# dummy div for adminmenu formatting css quirk %>
		    </div>
		    <div class="small-4 columns text-right">
		      <%= link_to users_url do %>
		        All<br><strong>Users</strong> 
		      <% end %>
		    </div>
		    <div class="small-8 columns text-left">
		      <strong><%=@user.email%></strong>
		    </div>
		  </div>
		  
		  <div class="small-2 columns rightadminmenu">
		    <div class="small-12 columns text-left end admin-nav-active">
		      Edit<br><strong>User</strong>
		    </div>
		  </div>

		  <div class="small-3 columns">
			  &nbsp;
		  </div>

      <div class="small-3 columns text-right rightadminmenu">
        Los Angeles Controller <strong>Audits</strong><br>
        Welcome, <strong><%= @current_user.email %></strong><br>
        <%= link_to 'Logout', logout_url %>
      </div>

    </div>
  </div>
</div>		  

<% end %>

app/views/users/index.html.erb
<% content_for :title do %>
  Users List
<% end %>



<div class="row">
	<div class="small-10 small-centered columns">
		<h2>All<br><strong>Users</strong></h2>
		<div class="AdminSectionSpacer"></div>

		<% if flash[:notice] %>

				<div data-alert class="alert-box success round">
			  	<%= flash[:notice] %>
				  <a href="#" class="close">&times;</a>
				</div>
		<% end %>

		<%= render partial: @users, spacer_template: "shared/indexspacer" %>

	</div>
</div>


<% content_for :admin_footer do %>
<!-- BEGIN SECTION SPACER -->
<div class="RASectionSpacer">

</div>
<!-- END SECTION SPACER -->
<div id="adminfooter">
  <div class="wrap">
    <div class="row">

			<div class="small-5 columns">
				<div class="small-5 columns leftadminmenu">
					<div class="small-12 columns text-center leftadminhead">
						<strong>Audits</strong>
					</div>
					<div class="small-6 columns text-right">
						<%= link_to audits_url do %>
							All<br><strong>Audits</strong> 
						<% end %>
					</div>
					<div class="small-6 columns text-left">
						<%= link_to new_audit_url do %>
							Create<br><strong>Audit</strong>
						<% end %>
					</div>
				</div>

				<div class="small-5 columns leftadminmenu">
					<div class="small-12 columns text-center leftadminhead activehead">
						<strong>Users</strong>
					</div>
					<div class="small-6 columns text-right admin-nav-active">

							All<br><strong>Users</strong>

					</div>
					<div class="small-6 columns text-left">
						<%= link_to new_user_url do %>
							Create<br><strong>User</strong>
						<% end %>
					</div>
				</div>
			</div>

			<div class="small-4 columns text-right">
			</div>

      <div class="small-3 columns text-right rightadminmenu">
        Los Angeles Controller <strong>Audits</strong><br>
        Welcome, <strong><%= @current_user.email %></strong><br>
        <%= link_to 'Logout', logout_url %>
      </div>

    </div>
  </div>
</div>
<% end %>

app/views/users/new.html.erb
<div class="row">
	<div class="small-9 small-centered columns">

		<h2>New<br><strong>User</strong></h2>
		<div class="AdminSectionSpacer"></div>


		<div class="row">
			<div class="small-6 columns">
				<% if flash[:notice] %>
					<div data-alert class="alert-box alert round">
						<%= flash[:notice] %>
					  <a href="#" class="close">&times;</a>
					</div>
				<% end %>

				<%= form_for @newuser, url: users_path do |f| %>
				<%= f.text_field :email %>
				<%= f.password_field :password %>
				<%= f.password_field :password_confirmation %>
				<%= f.submit 'Submit', class: "tiny radius success button" %> <%= link_to 'Cancel', users_path, class: "tiny radius info button"  %>
				<% end %>
			</div>
		</div>

	</div>
</div>


<% content_for :admin_footer do %>
 
<!-- BEGIN SECTION SPACER -->
<div class="RASectionSpacer">

</div>
<!-- END SECTION SPACER -->
<div id="adminfooter">
  <div class="wrap">
    <div class="row">

			<div class="small-9 columns">

				<div class="small-4 columns leftadminmenu">
					<div class="small-12 columns text-center leftadminhead">
						<strong>Audits</strong>
					</div>
					<div class="small-6 columns text-right">
						<%= link_to audits_url do %>
							All<br><strong>Audits</strong>
						<% end %>
					</div>
					<div class="small-6 columns text-left">
						<%= link_to new_audit_url do %>
							Create<br><strong>Audit</strong>
						<% end %>
					</div>
				</div>
				
				<div class="small-1 column">&nbsp;</div>
				
				<div class="small-3 columns leftadminmenu">
					<div class="small-12 columns text-center leftadminhead activehead">
						<strong>Users</strong>
					</div>
					<div class="small-6 columns text-right">
						<%= link_to users_url do %>
							All<br><strong>Users</strong>
						<% end %>
					</div>
					<div class="small-6 columns text-left admin-nav-active">
						
							Create<br><strong>User</strong>
						
					</div>
				</div>

				<div class="small-1 column">&nbsp;</div>
				

				<div class="small-3 columns leftadminmenu end">

						<div class="small-12 columns text-center leftadminhead">
							<strong>Shared Media Library</strong>
						</div>
						
						<div class="small-12 columns text-center end">
							<%= link_to shared_media_library_url do %>
								View<br><strong>Library</strong>
							<% end %>
						</div>
						
				</div>

			</div>

      <div class="small-3 columns text-right rightadminmenu">
        Los Angeles Controller <strong>Audits</strong><br>
        Welcome, <strong><%= @current_user.email %></strong><br>
        <%= link_to 'Logout', logout_url %>
      </div>

    </div>
  </div>
</div>


<% end %>