config/routes.rb
Rails.application.routes.draw do

root 'audits#index'
get '/404audit', :to => redirect('/404audit.html')

get '/login' => 'session#new', as: 'login'
post '/login' => 'session#create'
get '/logout' => 'session#destroy', as: 'logout'

resources :audits, only: [:new, :create, :index, :destroy, :update]
get 'audits/:id/edit/:subtype' => 'audits#edit', as: 'edit_audit'

resources :five_minute_summaries, only: [:show, :edit, :update]
resources :content_blocks, only: [:edit, :update, :destroy]
resources :background_photos, only: [:show, :destroy]

resources :users, only: [:new, :create, :edit, :update, :destroy, :index]

get '/shared_media_library' => 'shared_media_library#index', as: 'shared_media_library'
get '/shared_media_library/:id' => 'shared_media_library#show', as: 'shared_media_library_item'
post '/shared_media_library' => 'shared_media_library#create'
delete '/shared_media_library/:id' => 'shared_media_library#destroy'

get '/:audit_id/media_library' => 'media_library#index', as: 'media_library'
get '/:audit_id/media_library/:id' => 'media_library#show', as: 'media_library_item'
post '/:audit_id/media_library' => 'media_library#create'
delete '/:audit_id/media_library/:id' => 'media_library#destroy'


get '/content_blocks/new/:sectionid/:position' => 'content_blocks#new', as: 'new_content_block'
post '/content_blocks/new/:sectionid/:position' => 'content_blocks#create'

post '/content_blocks/cbhelper/:helper_type' => 'content_blocks#cbhelper', as: 'content_block_helper'

resources :full_audits, only: [:show, :edit, :update]
resources :sections, only: [:edit, :update, :destroy]

get '/sections/new/:full_audit_id/:position' => 'sections#new', as: 'new_section'
post '/sections/new/:full_audit_id/:position' => 'sections#create'

get 'publish/:switch/:id' => 'public_views#publish', as: 'publish'


get '/public/audits/:id/five_minute_summary' => 'public_views#fms', as: 'public_five_minute_summary'
get '/public/audits/:id/full_audit' => 'public_views#fa', as: 'public_full_audit'

end

app/models/audit.rb
class Audit
  include Mongoid::Document
  field :name, type: String
  field :publication_date, type: Date

  validates :name, presence: true, uniqueness: true
	validates :publication_date, presence: true

  has_one :five_minute_summary, :dependent => :destroy
  has_one :full_audit, :dependent => :destroy
  has_many :inline_photos, :dependent => :destroy

  has_one :public_five_minute_summary, class_name: 'PublicContent', :dependent => :destroy, inverse_of: :public_five_minute_summary_audit
  has_one :public_full_audit, class_name: 'PublicContent', :dependent => :destroy, inverse_of: :public_full_audit_audit

# has_many :posted_to_user, class_name: "Post", inverse_of: :posted_to

  def generate_new_fms

  		sections = {
  			'FMSsummary' => 'Summary',
  			'FMSbackground' => 'Background',
  			'FMSfindings' => 'Findings and Recommendations'
  		}

  		self.five_minute_summary.section_order = Array.new
  		sections.each do |st, dn|
	  		newsection = Section.new(section_type: st, display_name: dn)
        newsection.save!
        newsection.setcontent
	   		self.five_minute_summary.sections << newsection
	   		self.five_minute_summary.section_order << newsection.id
	   	end 
	   	self.five_minute_summary.save!

  end

  def generate_new_fa

    # default section setup
    sections = [
      'Executive Summary',
      'Audit Action Plan',
      'Introduction and Background',
      'Findings and Recommendations'
    ]

    self.full_audit.section_order = Array.new
    sections.each do |dn|
      newsection = Section.new(section_type: 'full_audit_section', display_name: dn)
      newsection.save!
      newsection.setcontent
      self.full_audit.sections << newsection
      self.full_audit.section_order << newsection.id
    end 
    self.full_audit.save!

  end

  def published?
    # checking if any of the needed sections are missing before allowing viewing
    published = false
    if self.public_five_minute_summary && self.public_full_audit
      unless self.public_five_minute_summary.public_sections.empty? || self.public_full_audit.public_sections.empty?
        published = true
      end
    end
  end

end

app/controllers/audits_controller.rb
class AuditsController < ApplicationController

  layout "admin"

  def new
  	@audit = Audit.new
  end

  def create

  	new_audit = Audit.create(audit_parameters)
  	if new_audit.valid?
   		new_audit.five_minute_summary = FiveMinuteSummary.new
   		new_audit.generate_new_fms
    	new_audit.full_audit = FullAudit.new
      new_audit.generate_new_fa
      redirect_to audits_path, notice:  "You have successfully created a new audit."
    else
    	@errors = new_audit.errors
    	flash.now[:notice] = "Sorry there was an error. Your audit was not created."
    	@audit = Audit.new
      render action: "new"
    end

  end

  def edit
    @audit = Audit.find(params[:id])
    @subtype = params[:subtype]

    # Set UI correctly for each audit type
    case @subtype
    when 'fms'
      @linkback = edit_five_minute_summary_url(@audit.five_minute_summary)
      @audit_typename = 'Five Minute Summary'
    when 'fa'
      @linkback = edit_full_audit_url(@audit.full_audit)
      @audit_typename = 'Full Audit'
    end

  end

  def update
    audit = Audit.find(params[:id])
    subtype = params[:subtype]

    audit.update(audit_parameters)

    if subtype == 'fms' 
      redirect_to edit_five_minute_summary_url(audit.five_minute_summary)
    else
      redirect_to edit_full_audit_url(audit.full_audit)
    end
    # redirect_to audits_path

  end

  def index
  	@audits = Audit.all
  end

  def destroy
    audit_to_destroy = Audit.find(params[:id])
    audit_to_destroy.destroy
    redirect_to audits_path, notice:  "You have successfully deleted the audit."

  end

  private
  def audit_parameters
    params.require(:audit).permit(:name, :publication_date)
  end

end

app/helpers/audits_helper.rb
module AuditsHelper


end

app/views/audits/_audit.html.erb
<div class="row">

	<div class="medium-4 columns">
		<strong><%= simple_format(audit.name, {}, wrapper_tag: "div") %></strong>
		<%= audit.publication_date.strftime("%B %d, %Y") %>
	</div>

	<div class="medium-8 columns">

		<div class="row">
			<div class="small-12 columns">
				<div class="medium-3 columns">
					<%= link_to five_minute_summary_url(audit.five_minute_summary) do %>
						<small><i class="fi-eye"></i> View/Edit Audit</small>
					<% end %><br/>
					<a href="#" data-reveal-id="myModal_<%= audit.id %>" class="deletelink">
						<small><i class="fi-x"></i> Delete this Audit</small>
					</a>
				</div>
				<div class="medium-4 columns">
					<% if audit.published? %>
						<%= link_to publish_url(1, audit) do %>
							<small><i class="fi-plus"></i> Update Audit</small><br/>
						<% end %>					
						<%= link_to publish_url(0, audit) do %>
							<small><i class="fi-minus"></i> Un-publish Audit</small>
						<% end %>
					<% else %>
						<%= link_to publish_url(1, audit) do %>
							<small><i class="fi-plus"></i> Publish Audit</small>
						<% end %>
					<% end %>
				</div>
				<div class="medium-5 columns text-right">
					<% if audit.published? %>
						<small>
							<span class="label success">Published</span><br>
								(<%= audit.public_five_minute_summary.c_at.strftime("at %I:%M%p %Z on %m/%d/%Y") %>)
						</small>
					<% else %>
						<small>
							<span class="label secondary">Not Published</span>
						</small>	
					<% end %>

				</div>
			</div> <!-- .small-12 -->
		</div> <!-- .row -->

	</div> <!-- .medium-8 -->

</div>

<div class="row">
	<div class="small-12 large-9 large-offset-3 columns">
		<% if audit.published? %>
		<div class="backpanel">
			<small><strong>Public Audit URL</strong></small> 
			<br>
			<small> Use this URL to distribute the Public Version of the Audit</small>
			<input type="text" value="<%= public_five_minute_summary_url(audit) %>">		
			<%= link_to public_five_minute_summary_url(audit), :target => :_blank do %>
				<small><i class="fi-eye"></i> View Public Audit in new tab</small>
			<% end %>	
		</div>
		<% end %>
	</div> <!-- .small-12 -->

</div> <!-- .row -->

<div id="myModal_<%= audit.id %>" class="reveal-modal small" data-reveal>
	<h2>Delete <strong>Audit</strong></h2>
  	<div class="AdminSectionSpacer1"></div>
  	<h4><strong><%= simple_format(audit.name, {}, wrapper_tag: "div") %></strong></h4>

		<h6>Are you sure you want to delete this audit?<br>
			<strong style="color: red;">All Deletions are Final</strong>
		</h6>
		<div class="AdminSectionSpacer1"></div>
  <%= button_to "Yes, Delete", audit_path(audit), :method => 'delete', data: { :confirm => 'Are you sure you want to delete this audit?'} , class: "tiny radius alert button" %> <a class="tiny radius info button custom-close-reveal-modal">No, I've changed my mind!!!</a>
  <a class="close-reveal-modal">&#215;</a>
</div>

app/views/audits/_audits_spacer.html.erb
<div class="listspacer"></div>

app/views/audits/edit.html.erb
<% content_for :title do %>
  Edit Audit - <%= @audit.name %>
<% end %>


<div class="row">
  <div class="small-10 small-centered columns">

    <%= form_for @audit, url: audit_url do |f| %>
    <%= hidden_field_tag 'subtype', @subtype %>
      <div class="backpanel">
      <div class="headWrapper topHead">
        <div class="row" id="WPtop">
          <div class="small-10 columns small-centered RAmargintop">
            <div class="headback">
              <div class="row">
                <div class="small-12 columns">
                  <%= f.text_area :name, rows: 5, style: "font-size:2em; font-weight:bold;", :required => true %>
                </div>
              </div>
              <h3>&mdash; Five Minute Summary &mdash;</h3>
              <div class="row">
                <div class="small-4 columns">
                  <%= f.date_field :publication_date, width: '10', :required => true  %>
                </div>
                <div class="small-8 columns">
                  <object type="image/svg+xml" data="/img/RGsig.svg" width="275" class="rgsig">
                    RG Signature <!-- fallback image in CSS -->
                  </object>
                </div>
              </div>
              <!-- <h3>Ron Galperin <small>City Controller</small></h3> -->
            </div>
          </div>
        </div>
      </div>
      </div>
      <%= f.submit 'Update', class: "tiny radius success button" %> <%= link_to 'Cancel (Discard changes)', @linkback, class: "tiny radius info button" %>
    <% end %>
	
  </div>
</div>


<!-- BEGIN SECTION SPACER -->
<div class="RASectionSpacer">

</div>
<!-- END SECTION SPACER -->
<% content_for :admin_footer do %>

<div id="adminfooter">
  <div class="wrap">
    <div class="row">


      <div class="small-3 columns leftadminmenu">
        <div class="small-3 columns text-right">
          <%= link_to @linkback do %>
            <small><strong>Cancel</strong><br> (Discard changes)</small>
          <% end %>
        </div>
        <div class="small-9 columns text-left">
          <%= @audit_typename %> | Edit Audit Title / Date <strong><%= simple_format(@audit.name, {}, wrapper_tag: "div").gsub(/\n/, '').html_safe %></strong>
        </div>
      </div>

      <div class="small-9 columns rightadminmenu">
        <div class="small-2 columns text-left inactive">
          View<br><strong>Five Minute Summary</strong>
        </div>
        <div class="small-2 columns text-left inactive">
          Edit<br><strong>Five Minute Summary</strong>
        </div>
        <div class="small-2 columns text-left inactive">
          View<br><strong>Full Audit</strong>
        </div>
        <div class="small-2 columns text-left inactive">
          Edit<br><strong>Full Audit</strong>
        </div>
        <div class="small-1 columns text-left inactive">
          Media<br><strong>Library</strong>
        </div>
        <div class="small-3 columns text-right">
          Los Angeles Controller <strong>Audits</strong><br>
          Welcome, <strong><%= @current_user.email %></strong><br>
          <%= link_to 'Logout', logout_url %>
        </div>    
      </div>

    </div>
  </div>
</div>

<% end %>

app/views/audits/index.html.erb
<% content_for :title do %>
  Audits List
<% end %>



<div class="row">
	<div class="small-10 small-centered columns">
		<h2>Los Angeles City Controller<br><strong>Audits</strong></h2>
		<div class="AdminSectionSpacer"></div>

		<% if flash[:notice] %>

				<div data-alert class="alert-box success round">
			  	<%= flash[:notice] %>
				  <a href="#" class="close">&times;</a>
				</div>
		<% end %>

		<%= render partial: "audit", collection: @audits, spacer_template: "shared/indexspacer" %>

	</div>
</div>


<% content_for :admin_footer do %>
  
<!-- BEGIN SECTION SPACER -->
<div class="RASectionSpacer">

</div>
<!-- END SECTION SPACER -->
<div id="adminfooter">
  <div class="wrap">
    <div class="row">

			<div class="small-9 columns">

				<div class="small-4 columns leftadminmenu">
					<div class="small-12 columns text-center leftadminhead activehead">
						<strong>Audits</strong>
					</div>
					<div class="small-6 columns text-right admin-nav-active">
						
							All<br><strong>Audits</strong>
						
					</div>
					<div class="small-6 columns text-left">
						<%= link_to new_audit_url do %>
							Create<br><strong>Audit</strong>
						<% end %>
					</div>
				</div>
				
				<div class="small-1 column">&nbsp;</div>
				
				<div class="small-3 columns leftadminmenu">
					<div class="small-12 columns text-center leftadminhead">
						<strong>Users</strong>
					</div>
					<div class="small-6 columns text-right">
						<%= link_to users_url do %>
							All<br><strong>Users</strong>
						<% end %>
					</div>
					<div class="small-6 columns text-left">
						<%= link_to new_user_url do %>
							Create<br><strong>User</strong>
						<% end %>
					</div>
				</div>
				
				<div class="small-1 column">&nbsp;</div>

				<div class="small-3 columns leftadminmenu end">

						<div class="small-12 columns text-center leftadminhead">
							<strong>Shared Media Library</strong>
						</div>
						
						<div class="small-12 columns text-center end">
							<%= link_to shared_media_library_url do %>
								View<br><strong>Library</strong>
							<% end %>
						</div>
						
				</div>

			</div>

      <div class="small-3 columns text-right rightadminmenu">
        Los Angeles Controller <strong>Audits</strong><br>
        Welcome, <strong><%= @current_user.email %></strong><br>
        <%= link_to 'Logout', logout_url %>
      </div>

    </div>
  </div>
</div>

<% end %>

app/views/audits/new.html.erb
<div class="row">
	<div class="small-9 small-centered columns">

		<h2>Create<br><strong>Audit</strong></h2>
		<div class="AdminSectionSpacer"></div>



		<div class="row">
			<div class="small-6 columns">
				<% if flash[:alert] %>
					<div data-alert class="alert-box alert round">
				  	<%= flash[:alert] %>
					  <a href="#" class="close">&times;</a>
					</div>
				<% end %>				
				<% if flash[:notice] %>
					<div data-alert class="alert-box alert round">
				  	<%= flash[:notice] %>
					  <a href="#" class="close">&times;</a>
					</div>
				<% end %>
				<% if @errors %>
					<div data-alert class="alert-box warning radius">
						<strong>Here's Why:</strong><br>		
							<% @errors.each do |k,v| %>
								<%= k %> <%= v %><br>
							<% end %>
					  <a href="#" class="close">&times;</a>
					</div>
				<% end %>				
				<%= form_for @audit do |f| %>
					<%= f.text_area :name, cols: 20, rows: 5 %>
					<%= f.label :publication_date %>
					<%= f.date_field :publication_date %>
					<%= f.submit 'Create New Audit', class: "tiny radius success button" %> <%= link_to 'Cancel', audits_path, class: "tiny radius info button"  %>

				<% end %>
			</div>
		</div>

	</div>
</div>


<% content_for :admin_footer do %>


<!-- BEGIN SECTION SPACER -->
<div class="RASectionSpacer">

</div>
<!-- END SECTION SPACER -->
<div id="adminfooter">
  <div class="wrap">
    <div class="row">

			<div class="small-9 columns">

				<div class="small-4 columns leftadminmenu">
					<div class="small-12 columns text-center leftadminhead activehead">
						<strong>Audits</strong>
					</div>
					<div class="small-6 columns text-right">
						<%= link_to audits_url do %>
							All<br><strong>Audits</strong>
						<% end %>
					</div>
					<div class="small-6 columns text-left admin-nav-active">
						
							Create<br><strong>Audit</strong>
						
					</div>
				</div>
				
				<div class="small-1 column">&nbsp;</div>
				
				<div class="small-3 columns leftadminmenu">
					<div class="small-12 columns text-center leftadminhead">
						<strong>Users</strong>
					</div>
					<div class="small-6 columns text-right">
						<%= link_to users_url do %>
							All<br><strong>Users</strong>
						<% end %>
					</div>
					<div class="small-6 columns text-left">
						<%= link_to new_user_url do %>
							Create<br><strong>User</strong>
						<% end %>
					</div>
				</div>
				
				<div class="small-1 column">&nbsp;</div>

				<div class="small-3 columns leftadminmenu end">

						<div class="small-12 columns text-center leftadminhead">
							<strong>Shared Media Library</strong>
						</div>
						
						<div class="small-12 columns text-center end">
							<%= link_to shared_media_library_url do %>
								View<br><strong>Library</strong>
							<% end %>
						</div>
						
				</div>

			</div>

      <div class="small-3 columns text-right rightadminmenu">
        Los Angeles Controller <strong>Audits</strong><br>
        Welcome, <strong><%= @current_user.email %></strong><br>
        <%= link_to 'Logout', logout_url %>
      </div>

    </div>
  </div>
</div>

<% end %>