config/routes.rb
Rails.application.routes.draw do

root 'audits#index'
get '/404audit', :to => redirect('/404audit.html')

get '/login' => 'session#new', as: 'login'
post '/login' => 'session#create'
get '/logout' => 'session#destroy', as: 'logout'

resources :audits, only: [:new, :create, :index, :destroy, :update]
get 'audits/:id/edit/:subtype' => 'audits#edit', as: 'edit_audit'

resources :five_minute_summaries, only: [:show, :edit, :update]
resources :content_blocks, only: [:edit, :update, :destroy]
resources :background_photos, only: [:show, :destroy]

resources :users, only: [:new, :create, :edit, :update, :destroy, :index]

get '/shared_media_library' => 'shared_media_library#index', as: 'shared_media_library'
get '/shared_media_library/:id' => 'shared_media_library#show', as: 'shared_media_library_item'
post '/shared_media_library' => 'shared_media_library#create'
delete '/shared_media_library/:id' => 'shared_media_library#destroy'

get '/:audit_id/media_library' => 'media_library#index', as: 'media_library'
get '/:audit_id/media_library/:id' => 'media_library#show', as: 'media_library_item'
post '/:audit_id/media_library' => 'media_library#create'
delete '/:audit_id/media_library/:id' => 'media_library#destroy'


get '/content_blocks/new/:sectionid/:position' => 'content_blocks#new', as: 'new_content_block'
post '/content_blocks/new/:sectionid/:position' => 'content_blocks#create'

post '/content_blocks/cbhelper/:helper_type' => 'content_blocks#cbhelper', as: 'content_block_helper'

resources :full_audits, only: [:show, :edit, :update]
resources :sections, only: [:edit, :update, :destroy]

get '/sections/new/:full_audit_id/:position' => 'sections#new', as: 'new_section'
post '/sections/new/:full_audit_id/:position' => 'sections#create'

get 'publish/:switch/:id' => 'public_views#publish', as: 'publish'


get '/public/audits/:id/five_minute_summary' => 'public_views#fms', as: 'public_five_minute_summary'
get '/public/audits/:id/full_audit' => 'public_views#fa', as: 'public_full_audit'

end

app/models/five_minute_summary.rb
class FiveMinuteSummary
  include Mongoid::Document

  field :section_order, type: Array # for display order of sections


  belongs_to :audit
  has_many :sections, :dependent => :destroy

  has_one :first_background_photo, class_name: 'BackgroundPhoto', :dependent => :destroy, inverse_of: :fms_bg_one
  has_one :second_background_photo, class_name: 'BackgroundPhoto', :dependent => :destroy, inverse_of: :fms_bg_two
  has_one :third_background_photo, class_name: 'BackgroundPhoto', :dependent => :destroy, inverse_of: :fms_bg_three
  has_one :fourth_background_photo, class_name: 'BackgroundPhoto', :dependent => :destroy, inverse_of: :fms_bg_four
  has_one :fifth_background_photo, class_name: 'BackgroundPhoto', :dependent => :destroy, inverse_of: :fms_bg_five

  embeds_one :public_content
  
	accepts_nested_attributes_for :sections, :audit

end

app/controllers/five_minute_summaries_controller.rb
class FiveMinuteSummariesController < ApplicationController

	layout :choose_layout

	def show
		@fms = FiveMinuteSummary.find(params[:id])

	end

	def edit
		@fms = FiveMinuteSummary.find(params[:id])

	end

	def update
		
		fms = FiveMinuteSummary.find(params[:id])

		if params[:five_minute_summary][:first_background_photo]
			set_bg_photo(fms, :first_background_photo, params[:five_minute_summary][:first_background_photo])
		end
		if params[:five_minute_summary][:second_background_photo]
			set_bg_photo(fms, :second_background_photo, params[:five_minute_summary][:second_background_photo])
		end
		if params[:five_minute_summary][:third_background_photo]
			set_bg_photo(fms, :third_background_photo, params[:five_minute_summary][:third_background_photo])
		end
		if params[:five_minute_summary][:fourth_background_photo]
			set_bg_photo(fms, :fourth_background_photo, params[:five_minute_summary][:fourth_background_photo])
		end
		if params[:five_minute_summary][:fifth_background_photo]
			set_bg_photo(fms, :fifth_background_photo, params[:five_minute_summary][:fifth_background_photo])
		end 

		redirect_to edit_five_minute_summary_path(fms)
	end

	private

	def choose_layout
		case action_name
		when 'show'
			'five_minute_summary'
		when 'edit'
			'admin'
		else
			'application'
		end
	end


end

app/views/five_minute_summaries/_fmsbackground.html.erb
<!-- BEGIN FIVE MINUTE SUMMARY SECTION BACKGROUND-->
<a name="background"></a>
<div class="sectionWrapper" id="WPbackground">
  <div class="row contentbg">

    <div class="small-12 medium-3 columns">
      <div class="RAfull">
        
        
        <h4 data-magellan-destination="background" class="text-right">BACKGROUND</h4>
      </div>
    </div>


    <div class="small-12 medium-9 columns">
      <div class="RAfull">

					<% unless thissection.content_blocks.empty? %>

						<% thissection.block_order.each_with_index do |bid, index| %>
							<% thisblock = thissection.content_blocks.find(bid) # iterate through content blocks in order%>
							
								<%= thisblock.content.html_safe %>
							
						<% end %>

					<% end %>


      </div>
    </div>
  </div>
</div>
<!-- END FIVE MINUTE SUMMARY SECTION BACKGROUND-->

app/views/five_minute_summaries/_fmsfindings.html.erb
<!-- BEGIN FIVE MINUTE SUMMARY SECTION OVERALL ASSESSMENT-->
<a name="overallassessment"></a>
<div class="sectionWrapper" id="WPoverallassessment">
<div class="row contentbg">

  <div class="small-12 medium-3 columns">
    <div class="RAfull">
      
      
      <h4 data-magellan-destination="overallassessment" class="text-right">OVERALL ASSESSMENT</h4> 
    </div>
  </div>

  <div class="small-12 medium-9 columns">
    <div class="RAfull">

					<% unless thissection.content_blocks.empty? %>

						<% thissection.block_order.each_with_index do |bid, index| %>
							<% thisblock = thissection.content_blocks.find(bid) # iterate through content blocks in order%>
							
								<%= thisblock.content.html_safe %>
							
						<% end %>

					<% end %>
  	</div>
	</div>
</div>
</div>
<!-- END FIVE MINUTE SUMMARY SECTION OVERALL ASSESSMENT-->

app/views/five_minute_summaries/_fmssummary.html.erb
<!-- BEGIN FIVE MINUTE SUMMARY SECTION INTRO-->


<div class="sectionWrapper" id="WPsummary">
  <div class="row contentbg">
    <div class="small-12 medium-10 columns small-centered">
      
      <div class="RAfull">
             
        <h4 data-magellan-destination="summary"></h4>
        <div id="backgroundShadeTop"></div>

				
					<% unless thissection.content_blocks.empty? %>

						<% thissection.block_order.each_with_index do |bid, index| %>
							<% thisblock = thissection.content_blocks.find(bid) # iterate through content blocks in order%>
							
								<%= thisblock.content.html_safe %>
							
						<% end %>

					<% end %>


        <div id="backgroundShadeBottom"></div>
      </div>
    </div>
  </div>
</div>
<!-- END FIVE MINUTE SUMMARY SECTION INTRO-->

app/views/five_minute_summaries/edit.html.erb
<% content_for :title do %>
  Five Minute Summary for <%= @fms.audit.name %>
<% end %>


<div class="row">
	<div class="small-12 columns">

		<h3>Title Panel</h3>
    <div class="backpanel">
    <div class="headWrapper topHead">
      <div class="row" id="WPtop">
        <div class="small-10 columns small-centered RAmargintop">
          <div class="headback">
                <h1><strong><%= simple_format(@fms.audit.name, {}, wrapper_tag: "div")  %></strong></h1>
                <h3>&mdash; Five Minute Summary &mdash;</h3>
                <h4><%= @fms.audit.publication_date.strftime("%B %d, %Y") %>
                <object type="image/svg+xml" data="/img/RGsig.svg" width="275" class="rgsig">
                  RG Signature <!-- fallback image in CSS -->
                </object></h4>
                <!-- <h3>Ron Galperin <small>City Controller</small></h3> -->
          </div>
        </div>
      </div>
    </div>
		<%= link_to edit_audit_url(@fms.audit, 'fms') do %>
			<i class="fi-pencil"></i> <small>Edit Title / Publication Date</small>
		<% end %>    
    </div>
		<!-- BEGIN SECTION SPACER -->
		<div class="AdminSectionSpacer">

		</div>
		<!-- END SECTION SPACER -->

		<%# display sections %>
		<% @fms.section_order.each do |sid| # iterate through sections in order%>
			<% thissection = @fms.sections.find(sid) %>
			<h3><%= thissection.display_name %></h3>

			<% if thissection.content_blocks.empty? %>
				<div class="backpanel">
					<%= link_to new_content_block_url(thissection.id, 0 ) do %>
						<i class="fi-plus"></i> <small>Add a block</small>
					<% end %>
				</div>
			<% else %>

			<% thissection.block_order.each_with_index do |bid, index| %>
				<% thisblock = thissection.content_blocks.find(bid) # iterate through content blocks in order%>
				<div class="backpanel">


					<p><%= thisblock.content.html_safe %></p>
					
					<%= link_to new_content_block_url(thissection.id, index ) do %>
						<i class="fi-arrow-up"></i> <small>Add a block before</small>
					<% end %>
					| 
					<%= link_to new_content_block_url(thissection.id, index + 1 ) do %>
						<i class="fi-arrow-down"></i> <small>Add a block after</small>
					<% end %>
					| 			
					<%= link_to edit_content_block_url(thisblock) do %>
						<i class="fi-pencil"></i> <small>Edit this block</small>
					<% end %>
					| 
					<a href="#" data-reveal-id="myModal_<%= bid %>" class="deletelink">
							<i class="fi-x"></i> <small>Delete this block</small>
					</a>

				</div>
				<div id="myModal_<%= bid %>" class="reveal-modal" data-reveal>
					<h2>Delete <strong>Content Block</strong></h2>
					<div class="AdminSectionSpacer1"></div>
				  <p class="lead"><%= thisblock.content.html_safe %></p>
				  <h6><strong>Are you sure you want to Delete This Content?</strong></h6>
				  <%= button_to "Yes, Delete this content", content_block_path(thisblock), :method => 'delete', class: "tiny radius alert button" %> <a class="tiny radius info button custom-close-reveal-modal">No, I've changed my mind!</a>
				  
				  <a class="close-reveal-modal">&#215;</a>
				</div>
			 <% end %>

			<% end %>
			<!-- BEGIN SECTION SPACER -->
			<div class="AdminSectionSpacer">

			</div>
			<!-- END SECTION SPACER -->
		<% end %>

		<div class="backpanel">
			<h3> Background Images </h3>
			<%= form_for @fms, url: five_minute_summary_path do |f| %>
				
				<div class="backpanel">
					<h4>First Background Photo</h4>
					<%= @fms.first_background_photo ? (render partial:'shared/bgimage', locals: { bgimage: @fms.first_background_photo }) : 'No Photo' %>
					<%= f.file_field :first_background_photo, label: "&nbsp;".html_safe %>
				</div>
				<div class="backpanel">
					<h4>Second Background Photo</h4>
					<%= @fms.second_background_photo ? (render partial:'shared/bgimage', locals: { bgimage: @fms.second_background_photo }) : 'No Photo' %>
					<%= f.file_field :second_background_photo, label: "&nbsp;".html_safe %>
				</div>
				<div class="backpanel">
					<h4>Third Background Photo</h4>
					<%= @fms.third_background_photo ? (render partial:'shared/bgimage', locals: { bgimage: @fms.third_background_photo }) : 'No Photo' %>
					<%= f.file_field :third_background_photo, label: "&nbsp;".html_safe %>
				</div>
				<div class="backpanel">
					<h4>Fourth Background Photo</h4>
					<%= @fms.fourth_background_photo ? (render partial:'shared/bgimage', locals: { bgimage: @fms.fourth_background_photo }) : 'No Photo' %>
					<%= f.file_field :fourth_background_photo, label: "&nbsp;".html_safe %>
				</div>
				<div class="backpanel">
					<h4>Fifth Background Photo</h4>
					<%= @fms.fifth_background_photo ? (render partial:'shared/bgimage', locals: { bgimage: @fms.fifth_background_photo }) : 'No Photo' %>
					<%= f.file_field :fifth_background_photo, label: "&nbsp;".html_safe %>
				</div>
				<%= f.submit 'Upload Background Images' %>

			<% end %>
		</div>
	</div>
</div>

<!-- BEGIN SECTION SPACER -->
<div class="RASectionSpacer">

</div>
<!-- END SECTION SPACER -->


<% content_for :admin_footer do %>
<div id="adminfooter">
	<div class="wrap">
		<div class="row">

			<div class="small-3 columns leftadminmenu">
				<div class="small-3 columns text-right">
			    <%= link_to audits_url do %>
			      <small>Back to All<br><strong>Audits</strong> </small>
			    <% end %>
				</div>
				<div class="small-9 columns text-left">
					<strong><%= simple_format(@fms.audit.name, {}, wrapper_tag: "span").gsub(/\n/, '').html_safe %></strong> 
				</div>
			</div>

			<div class="small-9 columns rightadminmenu">
				<div class="small-2 columns text-left">
					<%= link_to five_minute_summary_url(@fms) do %> 
						View<br><strong>Five Minute Summary</strong>
					<% end %>
				</div>
				<div class="small-2 columns text-left admin-nav-active">
					
						Edit<br><strong>Five Minute Summary</strong>
					
				</div>
				<div class="small-2 columns text-left">
					<%= link_to full_audit_url(@fms.audit.full_audit) do %>
						View<br><strong>Full Audit</strong>
					<% end %>
				</div>
				<div class="small-2 columns text-left">
					<%= link_to edit_full_audit_url(@fms.audit.full_audit) do %> 
						Edit<br><strong>Full Audit</strong>
					<% end %>
				</div>
				<div class="small-1 columns text-left">
					<%= link_to media_library_url(@fms.audit) do %> 
						Media<br><strong>Library</strong>
					<% end %>
				</div>
	      <div class="small-3 columns text-right">
	        Los Angeles Controller <strong>Audits</strong><br>
	        Welcome, <strong><%= @current_user.email %></strong><br>
	        <%= link_to 'Logout', logout_url %>
	      </div>
			</div>


		</div>
	</div>
</div>
<% end %>

app/views/five_minute_summaries/show.html.erb
<% content_for :title do %>
  <%= @fms.audit.name  %>
<% end %>
<% content_for :bodytitle do %>
  <%= simple_format(@fms.audit.name, {}, wrapper_tag: "div")  %>
<% end %>
<% content_for :publication_date do %>
  <%= @fms.audit.publication_date.strftime("%B %d, %Y") %>
<% end %>
<% content_for :full_audit_link do %><%= full_audit_path(@fms.audit.full_audit).html_safe %><% end %>

<% content_for :javascript_head do %>
	<%= javascript_tag do %>
		<% if @fms.first_background_photo %>
		  window.bgOne = '<%= j @fms.first_background_photo.photo(:large) %>';
		<% end %>  
		<% if @fms.second_background_photo %>
		  window.bgTwo = '<%= j @fms.second_background_photo.photo(:large) %>';
		<% end %>  
		<% if @fms.third_background_photo %>
		  window.bgThree = '<%= j @fms.third_background_photo.photo(:large) %>';
		<% end %>  
		<% if @fms.fourth_background_photo %>
		  window.bgFour = '<%= j @fms.fourth_background_photo.photo(:large) %>';
		<% end %>  
		<% if @fms.fifth_background_photo %>
		  window.bgFive = '<%= j @fms.fifth_background_photo.photo(:large) %>';
	  <% end %>
	<% end %>
<% end %>


<%# display sections %>
<% @fms.section_order.each do |sid| # iterate through sections in order%>

	<% thissection = @fms.sections.find(sid) %>
	
	<%= render partial: "/shared/fms_section", layout: "/shared/#{thissection.section_type.downcase}_layout", locals: {thissection: thissection} %>
	
	<!-- BEGIN SECTION SPACER -->
	<div class="RASectionSpacer">

	</div>
	<!-- END SECTION SPACER -->

<% end %>

<% content_for :admin_footer do %>

<div id="adminfooter">
	<div class="wrap">
		<div class="row">

			<div class="small-3 columns leftadminmenu">
				<div class="small-3 columns text-right">
			    <%= link_to audits_url do %>
			      <small>Back to All<br><strong>Audits</strong> </small>
			    <% end %>
				</div>
				<div class="small-9 columns text-left">
					<strong><%= simple_format(@fms.audit.name, {}, wrapper_tag: "span").gsub(/\n/, '').html_safe %></strong> 
				</div>
			</div>

			<div class="small-9 columns rightadminmenu">
				<div class="small-2 columns text-left admin-nav-active">
					View<br><strong>Five Minute Summary</strong>
				</div>
				<div class="small-2 columns text-left">
					<%= link_to edit_five_minute_summary_url(@fms) do %> 
						Edit<br><strong>Five Minute Summary</strong>
					<% end %>
				</div>
				<div class="small-2 columns text-left">
					<%= link_to full_audit_url(@fms.audit.full_audit) do %>
						View<br><strong>Full Audit</strong>
					<% end %>
				</div>
				<div class="small-2 columns text-left">
					<%= link_to edit_full_audit_url(@fms.audit.full_audit) do %> 
						Edit<br><strong>Full Audit</strong>
					<% end %>
				</div>
				<div class="small-1 columns text-left">
					<%= link_to media_library_url(@fms.audit) do %> 
						Media<br><strong>Library</strong>
					<% end %>
				</div>
	      <div class="small-3 columns text-right">
	        Los Angeles Controller <strong>Audits</strong><br>
	        Welcome, <strong><%= @current_user.email %></strong><br>
	        <%= link_to 'Logout', logout_url %>
	      </div>
			</div>


		</div>
	</div>
</div>

<% end %>